### ISSUE TITLE
Fix crash `ReferenceError: regeneratorRuntime is not defined` (staging)

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/muckr-web#33]

**Comment by cjolowicz** [comment]
https://github.com/babel/babel/issues/5085

**Comment by cjolowicz** [comment]
https://github.com/babel/babel/issues/5085#issuecomment-363242788

**Comment by cjolowicz** [comment]
```
$ heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
4:16:09 PM web.1 |  /Volumes/Data/Code/github.com/cjolowicz/muckr-web/lib/components/ArtistList.js:60
4:16:09 PM web.1 |        regeneratorRuntime.mark(function _callee() {
4:16:09 PM web.1 |        ^
4:16:09 PM web.1 |  ReferenceError: regeneratorRuntime is not defined
4:16:09 PM web.1 |      at /Volumes/Data/Code/github.com/cjolowicz/muckr-web/lib/components/ArtistList.js:60:7
4:16:09 PM web.1 |      at /Volumes/Data/Code/github.com/cjolowicz/muckr-web/lib/components/ArtistList.js:104:6
4:16:09 PM web.1 |      at Object.<anonymous> (/Volumes/Data/Code/github.com/cjolowicz/muckr-web/lib/components/ArtistList.js:134:2)
4:16:09 PM web.1 |      at Module._compile (internal/modules/cjs/loader.js:721:30)
4:16:09 PM web.1 |      at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
4:16:09 PM web.1 |      at Module.load (internal/modules/cjs/loader.js:620:32)
4:16:09 PM web.1 |      at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
4:16:09 PM web.1 |      at Function.Module._load (internal/modules/cjs/loader.js:552:3)
4:16:09 PM web.1 |      at Module.require (internal/modules/cjs/loader.js:657:17)
4:16:09 PM web.1 |      at require (internal/modules/cjs/helpers.js:22:18)
[DONE] Killing all processes with signal  SIGINT
4:16:09 PM web.1 Exited with exit code null
```
